# Site settings
title: Paoletti Law Blog
name: Paoletti Law Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  At Paoletti &amp; Gusmano, Attorneys at Law, our Bridgeport attorneys have criminal defense experience.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.paolettilaw.net/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
categories: [Articles, Drunk-Driving]
#gems: jekyll-lunr-js-search

# Build settings
markdown: kramdown


